name: Deploy
on:
  push:
    branches:
      - main
    # # Hanya men-trigger action jika ada perubahan di folder /controller
    # paths:
    #   - controller/**

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/merdeka-CI-CD
          git pull origin main
          docker-compose down
          docker-compose up --build -d